### ISSUE TITLE
Unnecessary try-catch-block

### ISSUE THREAD

**Issue by luca-schlecker** [TH-Projects/Rechner#26]
This try-catch-block should be removed:
https://github.com/TH-Projects/Rechner/blob/cacf2c94b1ce92ecabc4fb3562c58ad8e4b526f8/Rechner/UserInput.cs#L13-L28

If cathing exceptions other than a format was necessary, it should be done in `Modechoose` directly.

**Comment by TH-Projects** [comment]
you're right give me a monent to fix
